### ISSUE TITLE
Addon scaling broken

### ISSUE THREAD

**Issue by werkshy** [harrystech/dynosaur#14]
Actually scaling an addon is broken. I am disabling addon scalers in our config for now.

Looks like we just need to upgrade out platform-api usage.

<pre>
Expected([200, 201, 202, 204, 206, 304]) <=> Actual(422 Unprocessable Entity) 
/app/vendor/bundle/ruby/2.2.0/gems/excon-0.45.4/lib/excon/middlewares/expects.rb:6:in `response_call'
/app/vendor/bundle/ruby/2.2.0/gems/excon-0.45.4/lib/excon/middlewares/response_parser.rb:8:in `response_call'
/app/vendor/bundle/ruby/2.2.0/gems/excon-0.45.4/lib/excon/connection.rb:372:in `response'
/app/vendor/bundle/ruby/2.2.0/gems/excon-0.45.4/lib/excon/connection.rb:236:in `request'
/app/vendor/bundle/ruby/2.2.0/gems/heroics-0.0.14/lib/heroics/link.rb:60:in `run'
/app/vendor/bundle/ruby/2.2.0/gems/heroics-0.0.14/lib/heroics/resource.rb:27:in `method_missing'
/app/vendor/bundle/ruby/2.2.0/gems/platform-api-0.3.0/lib/platform-api/client.rb:539:in `update'
/app/vendor/bundle/ruby/2.2.0/bundler/gems/dynosaur-e1999cbd4b3b/lib/dynosaur/heroku_addon_manager.rb:22:in `set'
/app/vendor/bundle/ruby/2.2.0/bundler/gems/dynosaur-e1999cbd4b3b/lib/dynosaur/heroku_manager.rb:50:in `ensure_value'
/app/vendor/bundle/ruby/2.2.0/bundler/gems/dynosaur-e1999cbd4b3b/lib/dynosaur/controllers/papertrail_controller_plugin.rb:23:in `scale'
/app/vendor/bundle/ruby/2.2.0/bundler/gems/dynosaur-e1999cbd4b3b/lib/dynosaur/controllers/abstract_controller_plugin.rb:77:in `run'
</pre>

**Comment by pjambet** [comment]
I'll try to take a look at this, this used to work fine not so long ago :imp:

**Comment by felipekk** [comment]
Did you manage to find a fix? Just tried to use the gem and got the same problem.

**Comment by ACPK** [comment]
Is the gem currently working with Heroku?

**Comment by werkshy** [comment]
We are using dynosaur in production against our heroku app to scale dynos in response to GA Live API and NewRelic RPM data, but we are not using the Papertrail and Redis addon scalers. I believe this issue would need to be addressed before those would work.
